/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AlertsRouteImport } from './routes/alerts'
import { Route as AuditRouteImport } from './routes/audit'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as SimulateRouteImport } from './routes/simulate'
import { Route as MachinesIndexRouteImport } from './routes/machines/index'
import { Route as MachinesIdRouteImport } from './routes/machines/$id'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AlertsRoute = AlertsRouteImport.update({
  id: '/alerts',
  path: '/alerts',
  getParentRoute: () => rootRouteImport,
} as any)
const AuditRoute = AuditRouteImport.update({
  id: '/audit',
  path: '/audit',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const SimulateRoute = SimulateRouteImport.update({
  id: '/simulate',
  path: '/simulate',
  getParentRoute: () => rootRouteImport,
} as any)
const MachinesIndexRoute = MachinesIndexRouteImport.update({
  id: '/machines/',
  path: '/machines/',
  getParentRoute: () => rootRouteImport,
} as any)
const MachinesIdRoute = MachinesIdRouteImport.update({
  id: '/machines/$id',
  path: '/machines/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/alerts': typeof AlertsRoute
  '/audit': typeof AuditRoute
  '/dashboard': typeof DashboardRoute
  '/simulate': typeof SimulateRoute
  '/machines/$id': typeof MachinesIdRoute
  '/machines/': typeof MachinesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/alerts': typeof AlertsRoute
  '/audit': typeof AuditRoute
  '/dashboard': typeof DashboardRoute
  '/simulate': typeof SimulateRoute
  '/machines/$id': typeof MachinesIdRoute
  '/machines': typeof MachinesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/alerts': typeof AlertsRoute
  '/audit': typeof AuditRoute
  '/dashboard': typeof DashboardRoute
  '/simulate': typeof SimulateRoute
  '/machines/$id': typeof MachinesIdRoute
  '/machines/': typeof MachinesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/alerts'
    | '/audit'
    | '/dashboard'
    | '/simulate'
    | '/machines/$id'
    | '/machines/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/alerts'
    | '/audit'
    | '/dashboard'
    | '/simulate'
    | '/machines/$id'
    | '/machines'
  id:
    | '__root__'
    | '/'
    | '/alerts'
    | '/audit'
    | '/dashboard'
    | '/simulate'
    | '/machines/$id'
    | '/machines/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AlertsRoute: typeof AlertsRoute
  AuditRoute: typeof AuditRoute
  DashboardRoute: typeof DashboardRoute
  SimulateRoute: typeof SimulateRoute
  MachinesIdRoute: typeof MachinesIdRoute
  MachinesIndexRoute: typeof MachinesIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/alerts': {
      id: '/alerts'
      path: '/alerts'
      fullPath: '/alerts'
      preLoaderRoute: typeof AlertsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/audit': {
      id: '/audit'
      path: '/audit'
      fullPath: '/audit'
      preLoaderRoute: typeof AuditRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/simulate': {
      id: '/simulate'
      path: '/simulate'
      fullPath: '/simulate'
      preLoaderRoute: typeof SimulateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/machines/': {
      id: '/machines/'
      path: '/machines'
      fullPath: '/machines/'
      preLoaderRoute: typeof MachinesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/machines/$id': {
      id: '/machines/$id'
      path: '/machines/$id'
      fullPath: '/machines/$id'
      preLoaderRoute: typeof MachinesIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AlertsRoute: AlertsRoute,
  AuditRoute: AuditRoute,
  DashboardRoute: DashboardRoute,
  SimulateRoute: SimulateRoute,
  MachinesIdRoute: MachinesIdRoute,
  MachinesIndexRoute: MachinesIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
